#%RAML 1.0 NamedExample
value:
              Info:
                _lastNm: RAMIREZ
                _firstNm: FRANCISCO
                _midNm: ALARCON
                _sufNm: III
                _indvlPK: "2185634"
                _actvAGReg: Y
                _link: http://www.adviserinfo.sec.gov/IAPD/Individual/2185634
              OthrNms:
                OthrNm:
                  -
                    _lastNm: RAMIREZ
                    _firstNm: FRANK
                    _midNm: A
                  -
                    _lastNm: RAMIREZ
                    _firstNm: FRANCISCO
                    _midNm: ALARCON
                    _sufNm: III
                  -
                    _lastNm: RAMIREZ III
                    _firstNm: FRANCISCO
                    _midNm: A
              CrntEmps:
                CrntEmp:
                  -
                    CrntRgstns:
                      CrntRgstn:
                        -
                          _regAuth: TX
                          _regCat: RA
                          _st: APPROVED
                          _stDt: 2015-02-09
                    BrnchOfLocs:
                      BrnchOfLoc:
                        -
                          _str1: 2200 ROSS AVE
                          _str2: FLOOR 10
                          _city: DALLAS
                          _state: TX
                          _cntry: United States
                          _postlCd: "75201"
                        -
                          _str1: 383 MADISON AVENUE
                          _city: NEW YORK
                          _state: NY
                          _cntry: United States
                          _postlCd: "10179"
                    _orgNm: J.P. MORGAN SECURITIES LLC
                    _orgPK: "79"
                    _str1: 277 PARK AVENUE
                    _city: NEW YORK
                    _state: NY
                    _cntry: United States
                    _postlCd: "10172"
              Exms:
                Exm:
                  -
                    _exmCd: S63
                    _exmNm: Uniform Securities Agent State Law Examination
                    _exmDt: 1994-09-26
                  -
                    _exmCd: S65
                    _exmNm: Uniform Investment Adviser Law Examination
                    _exmDt: 1994-06-15
              PrevRgstns:
                PrevRgstn:
                  -
                    BrnchOfLocs:
                      BrnchOfLoc:
                        -
                          _city: DALLAS
                          _state: TX
                        -
                          _city: DALLAS
                          _state: TX
                        -
                          _city: HOUSTON
                          _state: TX
                    _orgNm: CREDIT SUISSE SECURITIES (USA) LLC
                    _orgPK: "816"
                    _regBeginDt: 2006-04-27
                    _regEndDt: 2014-10-24
                  -
                    BrnchOfLocs:
                      BrnchOfLoc:
                        -
                          _city: DALLAS
                          _state: TX
                    _orgNm: J.P. MORGAN SECURITIES INC.
                    _orgPK: "18718"
                    _regBeginDt: 2002-03-27
                    _regEndDt: 2004-04-06
                  -
                    BrnchOfLocs:
                      BrnchOfLoc:
                        -
                          _city: DALLAS
                          _state: TX
                        -
                          _city: DALLAS
                          _state: TX
                    _orgNm: CHASE INVESTMENT SERVICES CORP.
                    _orgPK: "25574"
                    _regBeginDt: 2005-02-03
                    _regEndDt: 2006-04-28
              EmpHss:
                EmpHs:
                  -
                    _fromDt: 04/2006
                    _toDt: 10/2014
                    _orgNm: CREDIT SUISSE SECURITIES (USA) LLC
                    _city: DALLAS
                    _state: TX
                  -
                    _fromDt: 01/2015
                    _orgNm: JP MORGAN SECURITIES, LLC
                    _city: NEW YORK
                    _state: NY
                  -
                    _fromDt: 10/2014
                    _orgNm: JPMORGAN CHASE BANK NA
                    _city: NEW YORK
                    _state: NY
                  -
                    _fromDt: 12/2005
                    _orgNm: THE RUNNING SPECIALTY GROUP DBA RUN ON!
                    _city: COPPELL
                    _state: TX
              OthrBuss:
                OthrBus:
                  _desc: "Entity Name: The Running Specialty Group, LLC dba Run On! Investment related: No  Address: Corporate: 231 Denver, CO www.run.com. Local: 680 Coppell, TX www.runontexas.com  Nature of the other business: Running stores offering shoes, apparel, gear, and training programs  Position/Title/Relationship: Distance training coach  Start Date: 19-Dec-2015  Approximate # of hours a month: 16-26  Approximate # of hours during securities trading hours: 0  Briefly describe your duties: I will be responsible for coaching running workouts for half and full marathon classes."